services:
  mysql:
    image: mysql:8.0
    container_name: rf_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rf_mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
