spring:
  application:
    name: restful-demo
  datasource:
    url: jdbc:mysql://localhost:3306/rf_mysql
    username: mysql
    password: mysql
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off

server: { port: 8088 }

api: { prefix: /api/v1 }
