spring:
  application:
    name: restful-demo
  datasource:
    url: jdbc:mysql://localhost:3306/restful-demo
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off

server: { port: 8080 }

api: { prefix: /api/v1 }
